name: pomo_pomo
description: A Very Good Project created by Very Good CLI.
version: 1.1.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  animated_bottom_navigation_bar: ^0.3.3
  animated_navigation_bar: ^0.0.5
  auto_route: ^4.0.1
  bloc: ^8.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_quill: ^5.0.3
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^1.3.0
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^10.1.0
  freezed_annotation: ^2.0.3
  google_fonts: ^3.0.1
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  hydrated_bloc: ^8.1.0
  intl: ^0.17.0
  isar_flutter_libs: ^2.5.0
  just_audio: ^0.9.24
  just_audio_windows: ^0.1.0
  local_storage_pomodoro_config_api:
    path: "./packages/local_storage_pomodoro_config_api"
  local_storage_task_api:
    path: "./packages/local_storage_task_api"
  path_provider: ^2.0.11
  percent_indicator: ^4.2.2
  pomo_pomo_theme:
    path: "./packages/pomo_pomo_theme"
  pomodoro_config_api:
    path: "./packages/pomodoro_config_api"
  pomodoro_config_repository:
    path: "./packages/pomodoro_config_repository"
  reactive_forms: ^13.0.0
  responsive_framework: ^0.2.0
  showcaseview: ^1.1.5
  simple_animations: ^4.1.0

  task_api:
    path: "./packages/task_api"
  task_repository:
    path: "./packages/task_repository"
  tuple: ^2.0.0

dev_dependencies:
  auto_route_generator: ^4.0.0
  bloc_test: ^9.0.3
  build_runner: ^2.1.11
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.9.3
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  mocktail: ^0.3.0
  msix: ^3.6.2
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - "assets/icons/"
    - "assets/audio/"
    - "assets/google_fonts/"
    - "assets/appainter_theme.json"

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/launcher_icon.png"

msix_config:
  display_name: Pomo Pomo - A Pomodoro Timer
  publisher_display_name: Paolo Matthew G. Tolentino
  identity_name: com.solstella.pomopomo
  msix_version: 1.0.0.0
  logo_path: "./assets/images/logo.png"
  certificate_path: "pomo_pomo_windows_certificate.pfx"
  certificate_password: pomo_pomo_rocks!
