name: local_storage_pomodoro_config_api
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  coverage: ^1.1.0
  freezed: ^2.0.3+1
  hive_generator: ^1.1.3
  json_serializable: ^6.2.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.0
dependencies:
  freezed_annotation: ^2.0.3
  hive: ^2.2.2
  pomodoro_config_api:
    path: ../pomodoro_config_api
