name: local_storage_task_api
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.1.11
  isar_generator: ^2.5.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
dependencies:
  isar: ^2.5.0
  isar_flutter_libs: ^2.5.0
  rxdart: ^0.27.4
  task_api:
    path: "../task_api"
