name: pomo_pomo_theme
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  json_theme: ^4.0.0+2
  responsive_framework: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.0
